version: "2.2"
x-defaults: &defaults
  build: .
  restart: unless-stopped
  volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app/src:ro # for develop
  environment:
      - RUN_ONCE=true
      - CRON_SCHEDULE=0 4 * * *

services:
  account1:
    <<: *defaults
    container_name: ${account1}
    image: ${account1}:latest
    volumes:
      - ./sessions/${account1}@hotmail.com:/app/sessions/${account1}@hotmail.com  # Optional but avoids re-logging in  # fixme Not working
      - ./config_${account1}.yaml:/app/config.yaml

